language: cpp
compiler: clang++-3.8

env:
  global:
    - CC="clang-3.8"
    - CXX="clang++-3.8"
    - CXXFLAGS="-stdlib=libc++"
    - LIBCXX_BUILD=1
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}"


script:
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} ..
  - make -j4

# Install Cmake 3.2.3
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - cmake-data
      - cmake
      - libboost-program-options1.55-dev
      - lcov
      - clang-3.8

notifications:
    slack: hoppergh:nlwIRc3VKMx48N1WtKfk24Pu
    email: false
