language: cpp

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.1/install
    - ${TRAVIS_BUILD_DIR}/gtest

env:
  global:
    - CC="clang-3.8"
    - CXX="clang++-3.8"
    - INSTALL_DIR=${DEPS_DIR}/b2
    - LIBCXX_BUILD=1
    - USE_LIBCXX=1
    - JOBS=3
    - BUILD_TYPE=Debug
    - BUILD_DIR=${TRAVIS_BUILD_DIR}/build

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - clang-3.8
      - clang-tidy-3.8
      - cmake
      - cmake-data
      - g++-5
      - gcc-5
      - lcov
      - python
      - valgrind

install:
  - JOBS=2
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"

cmake_command: &cmake_command |
      mkdir -p "${BUILD_DIR}"
      cd "${BUILD_DIR}"
      export CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                            -DCMAKE_C_COMPILER=clang-3.8 \
                            -DCMAKE_CXX_COMPILER=clang++-3.8 \
                            -DCMAKE_LINKER=clang++-3.8 \
                            -DCMAKE_CXX_FLAGS=${CXXFLAGS} \
                            -DGTEST_INSTALL_PATH=${TRAVIS_BUILD_DIR}/gtest"
      echo "CMake_options: ${CMAKE_OPTIONS}"
      cmake ${CMAKE_OPTIONS} ..

matrix:
  include:
    - script:
        - *cmake_command
        - |
          make -j${JOBS}
          make -j${JOBS} test
    - script:
        - *cmake_command
        - |
          make -j${JOBS} googletest
          python2 ${TRAVIS_BUILD_DIR}/tools/run-clang-tidy.py -p ${BUILD_DIR}  -header-filter="${TRAVIS_BUILD_DIR}/(src|test)" -j=${JOBS} -clang-tidy-binary=$(which clang-tidy-3.8)
    - script:
        - *cmake_command
        - ${TRAVIS_BUILD_DIR}/tools/clang-format.sh --check

notifications:
    slack:
      rooms:
        - hoppergh:nlwIRc3VKMx48N1WtKfk24Pu
      on_failure: always
      on_success: change
      on_pull_requests: false
    email: false
