language: cpp

env:
  global:
    - CC="clang-3.8"
    - CXX="clang++-3.8"
    - CXXFLAGS="-stdlib=libc++"
    - LIBCXX_BUILD=1
    - BUILD_TYPE=Debug
    - BUILD_DIR=${TRAVIS_BUILD_DIR}/build
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}"


script:
  - |
    makdir -p "${BUILD_DIR}"
    cd "${BUILD_DIR}"
    echo "${BUILD_DIR}"
    echo "${CMAKE_OPTIONS}"
    cmake ${CMAKE_OPTIONS} ..
    make -j4

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - cmake-data
      - cmake
      - libboost-program-options1.55-dev
      - lcov
      - clang-3.8

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.1/install

install:
  - JOBS=2
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  - |
    LLVM_VERSION="3.8.1"
    LLVM_ROOT="${DEPS_DIR}/llvm-${LLVM_VERSION}"
    LLVM_URL="http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz"
    LIBCXX_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxx-${LLVM_VERSION}.src.tar.xz"
    LIBCXXABI_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxxabi-${LLVM_VERSION}.src.tar.xz"
    if [[ -z "$(ls -A ${LLVM_ROOT}/install/include)" ]]; then
      mkdir -p "${LLVM_ROOT}" "${LLVM_ROOT}/build" "${LLVM_ROOT}/projects/libcxx" "${LLVM_ROOT}/projects/libcxxabi"
      travis_retry wget --quiet -O - "${LLVM_URL}" | tar --strip-components=1 -xJ -C "${LLVM_ROOT}"
      travis_retry wget --quiet -O - "${LIBCXX_URL}" | tar --strip-components=1 -xJ -C "${LLVM_ROOT}/projects/libcxx"
      travis_retry wget --quiet -O - "${LIBCXXABI_URL}" | tar --strip-components=1 -xJ -C "${LLVM_ROOT}/projects/libcxxabi"
      (cd "${LLVM_ROOT}/build" && cmake .. -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" -DCMAKE_INSTALL_PREFIX="${LLVM_ROOT}/install" -DCMAKE_BUILD_TYPE=$BUILD_TYPE)
      (cd "${LLVM_ROOT}/build/projects/libcxx" && make install -j$JOBS)
      (cd "${LLVM_ROOT}/build/projects/libcxxabi" && make install -j$JOBS)
    fi
    export CXXFLAGS="-I ${LLVM_ROOT}/install/include/c++/v1"
    export LDFLAGS="-L ${LLVM_ROOT}/install/lib -lc++ -lc++abi"
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${LLVM_ROOT}/install/lib"


notifications:
    slack: hoppergh:nlwIRc3VKMx48N1WtKfk24Pu
    email: false
