language: cpp
compiler: clang++

env:
  global:
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"


script:
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} ..
  - make -j4

# Install Cmake 3.2.3
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - boost-latest
    packages:
      - cmake-data
      - cmake
      - libboost-program-options1.55-dev
      - lcov

notifications:
    slack: hoppergh:nlwIRc3VKMx48N1WtKfk24Pu
    email: false
