language: cpp
dist: trusty

env:
  global:
    - CC="clang-4.0"
    - CXX="clang++-4.0"
    - CXXFLAGS="${CXXFLAGS} -stdlib=libc++"
    - LIBCXX_BUILD=1
    - JOBS=2
    - BUILD_TYPE=Debug
    - BUILD_DIR=${TRAVIS_BUILD_DIR}/build
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}"


script:
  - |
    mkdir -p "${BUILD_DIR}"
    cd "${BUILD_DIR}"
    cmake ${CMAKE_OPTIONS} ..
    make -j${JOBS} VERBOSE=1

before-install:
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x &&
    sudo apt-get update -qq

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - libboost-program-options1.55-dev
      - lcov
      - clang-4.0
      - g++-5
      - gcc-5

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.1/install

install:
  - sudo apt-get install -qq cmake cmake-data
  - JOBS=2
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - . ${TRAVIS_BUILD_DIR}/travis/install_libc++.sh


notifications:
    slack: hoppergh:nlwIRc3VKMx48N1WtKfk24Pu
    email: false
