language: cpp

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.1/install

env:
  global:
    - CC="clang-3.8"
    - CXX="clang++-3.8"
    - BOOST_VERSION="1.60.0"
    - BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
    - INSTALL_DIR=${DEPS_DIR}/b2
    - CXXFLAGS="${CXXFLAGS}"
    - LIBCXX_BUILD=1
    - USE_LIBCXX=1
    - JOBS=2
    - BUILD_TYPE=Debug
    - BUILD_DIR=${TRAVIS_BUILD_DIR}/build

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - cmake-data
      - cmake
      - lcov
      - clang-3.8
      - g++-5
      - gcc-5

install:
  - JOBS=2
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - . ${TRAVIS_BUILD_DIR}/travis/install_libc++.sh
  - . ${TRAVIS_BUILD_DIR}/travis/install_boost.sh

script:
  - |
    mkdir -p "${BUILD_DIR}"
    cd "${BUILD_DIR}"
    export CC="clang-3.8"
    export CXX="clang++-3.8"
    export CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                          -DCMAKE_C_COMPILER=${CC} \
                          -DCMAKE_CXX_COMPILER=${CXX} \
                          -DCMAKE_LINKER=${CXX} \
                          -DCMAKE_INCLUDE_PATH=${INSTALL_DIR} \
                          -DCMAKE_LIBRARY_PATH=${INSTALL_DIR}/lib \
                          -DBOOST_ROOT=${INSTALL_DIR}"
    echo "CMAKE_OPTIONS: " ${CMAKE_OPTIONS}
    cmake ${CMAKE_OPTIONS} ..
    VERBOSE=1 make -j${JOBS}

notifications:
    slack: hoppergh:nlwIRc3VKMx48N1WtKfk24Pu
    email: false
